import pickle

splashes=[
    "abotmin ask ammeter to ask icosahedron to staring cat react him", 
    "currently 78 splashes",
    "how to staring cat emoji",
    "every time bot enables it sends random text thats cool isnt",
    "im a workstahon mini",
    "silly proglet V1; cellua good indev2 xnopyt",
    "hello",
    "undefined is defined as undefined",
    "picardibot plays with my balls and likes it",
    "Also try icosahedron!",
    "did i leak my token",
    "nevermind",
    "cube is unrotatable cube",
    "prohressnet nowhen",
    "https://prohressnet.xtema5002x.repl.co",
    "https://prohressnet.xtema5002x.repl.co/src/eto_i_est_am_nyam.mp4",
    "i have a fact that will definitely shock you but im not gonna tell it because meh",
    "your mom will be deleted by ammeterhahahahhaha",
    "is team5002 real",
    "owner of this bot sometimes wants to be a jellyfish",
    "this splash was removed",
    "theres no progresstation and workstahon flag :skull:",
    "slinx's attic is the most silly discord server you DEFINITELY should join!!!!!!!",
    "\"breaking good\" - 💀💀💀\n\nthats a long story",
    "you're*",
    "jsab stands for **j**ust ||**s**illy **a**ss **b**alls||",
    "lets drink to the health of indie developers!!!!",
    '```py\nwhile True:\n    print("\\n")\n    h=open("splashes_channels.txt").read().split()\n    for every in h:\n        channel=bot.get_channel(int(every))\n        if channel!=None:\n            await channel.send(choice(splashes))\n            print(f"sending splash on {channel} ({channel.guild})")\n        else:\n            print("cant send splash 💀💀💀")\n            with open("splashes_channels.txt","w") as splasheschannels:\n                for everything in h:\n                    if everything!=every:\n                        splasheschannels.write(f"{everything}\\n")\n    print("\\n")\n    await asyncio.sleep(150)```',
    "workstindows 11 professional",
    "🧊",
    "RUSHING DEEZ CATS",
    "voltmatter2",
    "AUGUST 12 2036 THE HEAT DEATH OF THE UNIVERSE",
    "voltmeter killed proglet",
    "Ihatelampadaire",
    "расстрел",
    "https://tryitands.ee",
    "https://media.discordapp.net/attachments/1067491425484296292/1121410297052282931/cat_cat.gif",
    "I declare myself a 600amper power supply unit",
    "im sexually attracted to hydrogen uwu",
    "Tuctdioioeaern",
    "сигма сигма сигма",
    "hog rider attacks!!!!",
    "please do not forget to post cat next 19th date",
    "spider man cowboy 😅😍😄😅😄😊😄🤠🤠🤠",
    "google spread",
    "skull meoji",
    "сюжет очень затягивает, геймплей и графика просто шикарны, постоянно возвращаюсь в эту игру, 10/10",
    "<:p2aperture:1157321484797227108> Aperture Science Sanitizer 564.0.0 Pro Max Ultra Deluxe Bottle Java Edition x86 For Workstations Without SMS And Registration",
    "FRINKIFAIL BAD FRINKIFAIL BAD FRINKIFAIL BA",
    "Be there! Be square!",
    "Tema5002 is a city with the population of 197 million people. It is the capital city of Staring Cat Land.",
    "wamter",
    "the cells moved and i was like wow cool so that was yes play game now",
    "tellurium#8399",
    "Да кто такие эти ваши скибиди туалеты",
    "ампержопа",
    "Competing in пульт от ядерки",
    "https://balls.com/",
    "at the speed of lignt",
    "wouse wouse wouse wouse wouse wouse wouse wouse wouse wouse wouse wouse wouse wouse wouse wouse",
    "ULTRASKILLISSUE",
    "geomeyru dash",
    "HAHA YES I LEAKED ICOSAHEDRON TOKEN",
    "never call me that again stupid nig",
    "waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka",
    "<:ace_flag:1181617159210803330><:ace_flag:1181617159210803330><:ace_flag:1181617159210803330> people from this country are so cool omg",
    "guys lets cook the cake :)",
    "@germancountryball ты играеш в GTA 5",
    "dont go doin drugs kids",
    "Developer Sanity: 47%",
    "Hello hi sir thank",
    "do i really need to live milenakos mods?🤔🤔",
    "speaking fire🗣️🔥🗣️🔥",
    "люди гта 6 вийдет на консось нових поколеня",
    "<:fruit:1187076240612540588><a:arrow:1187076103353925684>",
    "polyehdron store :department_store::convenience_store::anguished::department_store:",
    "every time abotmin replies to ammeter he loses 1% of sanity. Please stop abotmin from replying to avoid insanity. #sanitymatters"
    ]

splashesinfo=[
    "me", "me",
    "me trying to realise how does disnake work",
    "me", "me", "me", "me", "me",
    "me (cring)",
    "me", "me",
    "guy wanted to help me with splashes and said this so yes",
    "me", "me", "me", "me", "me", 
    "minkos on sillyballs6969420",
    "me",
    "me after biology lesson",
    "who this could possibly be",
    "me", "me",
    "me after fixing ammeter's bugs",
    "me",
    "cube",
    "me", "me",
    "slinx92 somewhere",
    "rusher7629's display name on cat stand",
    "rusher7629 on cat stand",
    "me after calling ammeter antimatter",
    "me",
    "me after playing worms armageddon",
    "me", "me", "me", "me", "me", "me", 
    "crs25001 was saying something spamming and i copied first several symbols",
    "me", "me", "me",
    "me and slinx92",
    "someone",
    "me",
    "someone in steam reviews on sharex",
    "me", "me",
    "me after mc live 2023 trailer",
    "slinx92",
    "astroleaf in lampadaire's steam profile",
    "nathancrazy's review on cell machine indev",
    "me",
    "someone in telegram",
    "slinx92",
    "the teleporter cell's rich presence",
    "me",
    "cube on slinx's attic",
    "someone on cell machine server",
    "nicejs's status",
    "mileankos's review on geometry dash",
    "ME BEING INSANE",
    "slinx muting bobmaster69",
    "someone on cat stand",
    "me",
    "me (all asexuals are obsessed with cakes there is no exceptions)",
    "maranw on proglet software",
    "random mari0 mappack",
    "cmmm+ splash",
    "someone silly on pinterest",
    "itamar_nudge on milenakos mods in advertisement",
    "sushi2627 on cat stand #memes",
    "this video description: https://youtu.be/lM_qJsAvujg",
    "me",
    "slinx92",
    "either cube or slinx idk"
    ]

pickle.dump(splashes, open("splashes.dat", "wb"))
pickle.dump(splashesinfo, open("splashesinfo.dat", "wb"))
